name: alexa_cars_app
description: "Alexa Cars - Car Rental App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  carousel_slider: ^4.1.1
  shared_preferences: ^2.2.2
  http: ^1.1.2
  provider: ^6.1.1
  intl: ^0.19.0
  url_launcher: ^6.2.2
  flutter_rating_bar: ^4.0.1
  image_picker: ^1.0.5
  cached_network_image: ^3.3.1
  flutter_datetime_picker_plus: ^2.1.0
  font_awesome_flutter: ^10.6.0
  smooth_page_indicator: ^1.1.0
  flutter_spinkit: ^5.2.0
  flutter_native_splash: ^2.3.6
  animations: ^2.0.8
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/

  # Using Google Fonts instead of local font files
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Poppins-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700
